name: machine

on: [ push, workflow_dispatch ]

jobs:

  job_one:
    strategy:
      matrix:
        os_env:
          - macos-latest

        build_type:
          - Debug
          - Release

        scenario:
          - basic

    runs-on: ${{ matrix.os_env }}

    steps:
      - name: grab main project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: grab cmfkit
        uses: actions/checkout@v2
        with: 
          repository: ornl-fusion/cmfkit
          path: ./.cmfkit_base

      - name: launch build
        env:
          CMFKIT_PLATFORM:   github-vm-${{ matrix.os_env }}
          CMFKIT_SCENARIO:             ${{ matrix.scenario }}

          CMAKE_BUILD_TYPE:  ${{ matrix.build_type }}

        run: |
          ./.cmfkit_base/launch build

