---

name: olivine
on:
  issue_comment:
    types: [ created ]

jobs:
  job_one:
    runs-on: self-hosted

    steps:


      - name: Verify Actor
        env:
          ACTOR_TOKEN: ${{ secrets.TOKENIZER }}${{ github.actor }}${{ secrets.TOKENIZER }}
          ACTOR_ALLOW: ${{ secrets.ACTORLIST }}
        if: contains( env.ACTOR_ALLOW, env.ACTOR_TOKEN )
        id: check
        run: |
          echo "triggered=true" >> $GITHUB_OUTPUT

      - name: print vars
        run: |
          echo "$(date)" > olivine.txt

#      - name: GitHub API Request
#          if: steps.check.outputs.triggered == 'true'
#          id: request
#          uses: octokit/request-action@v2.1.9
#          with:
#            route: ${{github.event.issue.pull_request.url}}
#          env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


