---

name: olivine
on:
  issue_comment:
    types: [ created ]

jobs:
  job_one:
    runs-on: self-hosted

    steps:

      - name: Verify Actor
        env:
          ACTOR_TOKEN: ${{ secrets.TOKENIZER }}${{ github.actor }}${{ secrets.TOKENIZER }}
          ACTOR_ALLOW: ${{ secrets.ACTORLIST }}
        if: contains( env.ACTOR_ALLOW, env.ACTOR_TOKEN )
        id: check
        run: |
          echo "triggered=true" >> $GITHUB_OUTPUT

      - name: CI Debug
        if: steps.check.outputs.triggered == 'true'
        run: |
          env -0 | while IFS='' read -d '' line ; do printf '%s\t: %s\n' "${line%%=*}" "${line#*=}" | expand -t 30 | sed ':a;N;$!ba;s/\n/ /g'; done | LC_COLLATE=C sort -b > ./env_out.txt

      - name: GitHub API Request
          if: steps.check.outputs.triggered == 'true'
          id: request
          uses: octokit/request-action@v2.1.9
          with:
            route: ${{github.event.issue.pull_request.url}}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR status
          if: steps.check.outputs.triggered == 'true'
          uses: geekdude/github-status-action-v2@v1.1.10
          with:
            authToken: ${{ secrets.GITHUB_TOKEN }}
            context: "ci-gpu-AMD ${{ matrix.jobname }}"
            state: "pending"
            sha: ${{fromJson(steps.request.outputs.data).head.sha}}
            target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
