---

name: onyx
on:
  issue_comment:
    types: [ created ]

jobs:
  job_verify_actor:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Actor
        id: verify_actor
        env:
          ACTOR_TOKEN: ${{ secrets.TOKENIZER }}${{ github.actor }}${{ secrets.TOKENIZER }}
          ACTOR_ALLOW: ${{ secrets.ACTORLIST }}
        if: contains( env.ACTOR_ALLOW, env.ACTOR_TOKEN )
        run: |
          echo "allowed=true" >> $GITHUB_OUTPUT
    outputs:
      allowed: ${{ steps.verify_actor.outputs.allowed }}


  job_build:
    runs-on: ubuntu-latest
    needs: job_verify_actor
    steps:
      - name: show status 
        run: |
          echo "${{ needs.job_verify_actor.outputs.allowed == 'true' }}"



