name: spackbuild
on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: grab main project
        uses: actions/checkout@v2

      - name: grab spack
        uses: actions/checkout@v2
        with:
          repository: spack/spack
          path: ./spack

      - name: spack mirror cache
        id: spack-mirror-cache
        uses: actions/cache@v3
        with:
          path: ~/arcflash-mirror
          key: arcflash-mirror

      - if: ${{ steps.spack-mirror-cache.outputs.cache-hit != 'true' }}
        name: create mirror
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env create      -d ~/arcflash-spackenv
          spack env activate -p -d ~/arcflash-spackenv
          spack add zlib
          spack install
          spack mirror create   -d ~/arcflash-mirror --all
          spack env deactivate

      - name: spack install
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env create      -d ~/thunderclap-spackenv
          spack env activate -p -d ~/thunderclap-spackenv
          spack mirror add arcflash ~/arcflash-mirror
          spack mirror list
          spack add zlib
          spack install
          spack find
          spack env deactivate


          
        
