name: spack
on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: grab main project
        uses: actions/checkout@v4
        with:
          path: './KORC'

      - run: |
        pwd
        ls -la
        tree -L 2

