name: spackbuild
on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: grab main project
        uses: actions/checkout@v2

      - name: grab spack
        uses: actions/checkout@v2
        with:
          repository: spack/spack
          path: ./spack

      - name: spack build
        run: |
          . ./spack/share/spack/setup-env.sh
          mkdir -p ./spack/var/spack/repos/builtin/packages/korc
          cp ./spackpack/package.py ./spack/var/spack/repos/builtin/packages/korc
          spack list korc
          spack install korc
          ls -la
          pwd


