name: spack-buildcache
#on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: grab main project
        uses: actions/checkout@v2

      - name: grab spack
        uses: actions/checkout@v2
        with:
          repository: spack/spack
          path: ./spack

      - name: spack binary cache
        id: spack-buildcache
        uses: actions/cache@v3
        with:
          path: ~/mirror
          key: spack-buildcache-1

      - if: ${{ steps.spack-buildcache.outputs.cache-hit != 'true' }}
        name: create buildcache
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env activate -p -d ./
          spack add
          spack install
          spack mirror create -d ~/mirror --all
          spack env deactivate


      - name: build korc
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env activate -p -d ./
          spack mirror add nacho ~/mirror
          spack mirror remove spack-public
          spack mirror list
          spack add
          spack install
          spack find
          set -x
          which cmake
          which gfortran
          gfortran --version
          set +x
          spack env deactivate
