name: spackbuild
on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: grab main project
        uses: actions/checkout@v2

      - name: grab spack
        uses: actions/checkout@v2
        with:
          repository: spack/spack
          path: ./spack

      - name: spack setup
        run: |
          ls -la
          ls -la ./spack/share/spack/
          . ./spack/share/spack/setup-env.sh
          which spack
          spack --version

      - name: spack test
        run: |
          . ./spack/share/spack/setup-env.sh
          spack --version

      - name: spack build
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env activate -d ./spackenv-nacho
          spack find
          spack install

