name: spackbuild
on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: grab main project
        uses: actions/checkout@v2

      - name: grab spack
        uses: actions/checkout@v2
        with:
          repository: spack/spack
          path: ./spack

      - name: spack setup
        run: |
          ls -la ./spack/share/spack/
          . ./spack/share/spack/setup-env.sh
          which spack
          spack --version
          set -x
          df -h
          pwd -P
          lsblk
          findmnt


      - name: spack install
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env create      -d ~/thunderclap-spackenv
          spack env activate -p -d ~/thunderclap-spackenv
          spack find
          spack add zlib
          spack install

      - name: spack mirror
        run: |
          . ./spack/share/spack/setup-env.sh
          spack env status
          echo ---------------------
          spack mirror list



#          spack mirror create -d ~/thunderclap-mirror --all
#          spack env activate -d ./spackenv-nacho
